"""
Notebook Generator for AI Pipeline Service

Generates PySpark notebooks for:
- PII/PHI detection and masking using Presidio
- Data transformations
- Loading data to Lakehouse tables
"""

from __future__ import annotations
import base64
import json
import logging
from typing import Optional, List, Dict, Any

from services.ai_pipeline.models import (
    PipelineConfig,
    MaskingType,
    TransformationStep,
    TransformationType,
)

logger = logging.getLogger(__name__)


class NotebookGenerator:
    """
    Generates Fabric notebooks for data processing.

    Creates notebooks with:
    - PII detection and masking using Presidio
    - User-specified transformations
    - Data loading to Lakehouse
    """

    def __init__(self):
        """Initialize the notebook generator."""
        pass

    # =========================================================================
    # MAIN GENERATION METHOD
    # =========================================================================

    def generate_notebook(
        self,
        config: PipelineConfig,
        notebook_name: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate a complete notebook for the pipeline.

        Args:
            config: Pipeline configuration
            notebook_name: Optional notebook name

        Returns:
            Notebook definition in Fabric format
        """
        name = notebook_name or f"{config.pipeline_name}_Notebook"

        cells = []

        # Cell 1: Setup and imports
        cells.append(self._generate_setup_cell(config))

        # Cell 2: Configuration
        cells.append(self._generate_config_cell(config))

        # Cell 3: Read data
        cells.append(self._generate_read_data_cell(config))

        # Cell 4: Sample size logic (if PII enabled)
        if config.pii.enabled:
            cells.append(self._generate_sample_size_cell())

        # Cell 5: PII Detection (if enabled)
        if config.pii.enabled:
            cells.append(self._generate_pii_detection_cell())

        # Cell 6: Masking functions (if PII enabled)
        if config.pii.enabled:
            cells.append(self._generate_masking_functions_cell())

        # Cell 7: Apply masking (if PII enabled)
        if config.pii.enabled:
            cells.append(self._generate_apply_masking_cell(config))

        # Cell 8: Transformations (if any)
        if config.transformations.enabled:
            cells.append(self._generate_transformations_cell(config))

        # Cell 9: Write to destination
        cells.append(self._generate_write_cell(config))

        # Cell 10: Summary
        cells.append(self._generate_summary_cell(config))

        # Build notebook structure
        notebook = self._build_notebook_structure(name, cells)

        return notebook

    # =========================================================================
    # CELL GENERATORS
    # =========================================================================

    def _generate_setup_cell(self, config: PipelineConfig) -> Dict[str, Any]:
        """Generate the setup/imports cell."""

        if config.pii.enabled:
            code = '''# Cell 1: Setup and Imports
# ============================================================================
# This notebook was auto-generated by AI Pipeline Service
# ============================================================================

from pyspark.sql.functions import udf, col, lit
from pyspark.sql.types import StringType
import hashlib

# Presidio imports (requires presidio-env environment)
try:
    from presidio_analyzer import AnalyzerEngine
    from presidio_anonymizer import AnonymizerEngine
    from presidio_anonymizer.entities import OperatorConfig

    analyzer = AnalyzerEngine()
    anonymizer = AnonymizerEngine()
    PRESIDIO_AVAILABLE = True
    print("✓ Presidio loaded successfully")
except ImportError as e:
    PRESIDIO_AVAILABLE = False
    print(f"⚠ Presidio not available: {e}")
    print("  PII detection will be skipped")
'''
        else:
            code = '''# Cell 1: Setup and Imports
# ============================================================================
# This notebook was auto-generated by AI Pipeline Service
# ============================================================================

from pyspark.sql.functions import col, lit
from pyspark.sql.types import StringType

print("✓ Setup complete")
'''

        return self._create_cell(code, "Setup and Imports")

    def _generate_config_cell(self, config: PipelineConfig) -> Dict[str, Any]:
        """Generate the configuration cell."""

        pii_config = "None"
        if config.pii.enabled and config.pii.masking_type:
            # Handle both enum objects and string values
            masking_value = config.pii.masking_type.value if hasattr(config.pii.masking_type, 'value') else config.pii.masking_type
            pii_config = f'"{masking_value}"'

        # Handle file format (could be enum or string)
        file_format = config.source.file_format
        if hasattr(file_format, 'value'):
            file_format = file_format.value
        elif file_format is None:
            file_format = 'csv'

        code = f'''# Cell 2: Configuration
# ============================================================================
# Pipeline configuration - auto-generated from user input
# ============================================================================

CONFIG = {{
    # Source
    "source_path": "Files/raw/{config.source.folder_path or 'data'}/",
    "source_format": "{file_format}",

    # PII/PHI Settings
    "pii_enabled": {str(config.pii.enabled)},
    "masking_type": {pii_config},

    # Destination
    "output_table": "{config.destination.table_name or 'output_table'}",
    "write_mode": "{config.destination.write_mode}",
}}

print(f"Configuration loaded:")
print(f"  Source: {{CONFIG['source_path']}}")
print(f"  Format: {{CONFIG['source_format']}}")
print(f"  PII Detection: {{CONFIG['pii_enabled']}}")
print(f"  Output Table: {{CONFIG['output_table']}}")
'''

        return self._create_cell(code, "Configuration")

    def _generate_read_data_cell(self, config: PipelineConfig) -> Dict[str, Any]:
        """Generate the data reading cell."""

        # Handle both enum and string file format
        fmt = config.source.file_format
        if fmt:
            file_format = fmt.value if hasattr(fmt, 'value') else fmt
        else:
            file_format = "csv"

        if file_format == "csv":
            read_code = 'spark.read.format("csv").option("header", "true").option("inferSchema", "true").load(CONFIG["source_path"])'
        elif file_format == "parquet":
            read_code = 'spark.read.format("parquet").load(CONFIG["source_path"])'
        elif file_format == "json":
            read_code = 'spark.read.format("json").load(CONFIG["source_path"])'
        elif file_format == "delta":
            read_code = 'spark.read.format("delta").load(CONFIG["source_path"])'
        else:
            read_code = 'spark.read.format(CONFIG["source_format"]).load(CONFIG["source_path"])'

        code = f'''# Cell 3: Read Data
# ============================================================================

print(f"Reading data from: {{CONFIG['source_path']}}")

df = {read_code}

total_rows = df.count()
total_cols = len(df.columns)

print(f"✓ Data loaded successfully")
print(f"  Rows: {{total_rows:,}}")
print(f"  Columns: {{total_cols}}")
print(f"  Schema: {{df.columns}}")

# Show sample
df.limit(5).show(truncate=False)
'''

        return self._create_cell(code, "Read Data")

    def _generate_sample_size_cell(self) -> Dict[str, Any]:
        """Generate the AI sample size decision cell."""

        code = '''# Cell 4: AI-Decided Sample Size for PII Detection
# ============================================================================
# Sample size is determined based on data volume for efficient scanning
# ============================================================================

def get_sample_size(total_rows: int) -> int:
    """
    AI logic to decide sample size based on data volume.
    Balances between detection accuracy and performance.
    """
    if total_rows < 100:
        return total_rows  # Scan all rows for small datasets
    elif total_rows < 1000:
        return 10
    elif total_rows < 10000:
        return 50
    elif total_rows < 100000:
        return 100
    else:
        return 200

sample_size = get_sample_size(total_rows)
print(f"✓ AI decided sample size: {sample_size} rows (from {total_rows:,} total)")
'''

        return self._create_cell(code, "Sample Size Decision")

    def _generate_pii_detection_cell(self) -> Dict[str, Any]:
        """Generate the PII detection cell."""

        code = '''# Cell 5: Detect Sensitive Columns Using Presidio
# ============================================================================
# Scans sample data to identify columns containing PII/PHI
# ============================================================================

def detect_sensitive_columns(df, sample_size: int) -> list:
    """
    Scan sample rows and detect which columns contain PII/PHI.
    Uses Presidio analyzer to identify sensitive data patterns.

    Returns:
        List of dicts with column name and detected entity types
    """
    if not PRESIDIO_AVAILABLE:
        print("⚠ Presidio not available, skipping PII detection")
        return []

    sensitive_columns = []
    sample_df = df.limit(sample_size).toPandas()

    print(f"Scanning {len(sample_df)} rows across {len(sample_df.columns)} columns...")

    for column in sample_df.columns:
        is_sensitive = False
        detected_entities = set()

        for value in sample_df[column].dropna():
            # Skip non-string or empty values
            if value is None:
                continue

            text_value = str(value).strip()
            if not text_value:
                continue

            # Use Presidio to analyze
            try:
                results = analyzer.analyze(text=text_value, language='en')

                if results:
                    for r in results:
                        detected_entities.add(r.entity_type)
                    is_sensitive = True
                    break  # Found PII, no need to check more values

            except Exception as e:
                continue

        if is_sensitive:
            sensitive_columns.append({
                "column": column,
                "entities": list(detected_entities)
            })
            print(f"  ⚠ Sensitive: {column} -> {list(detected_entities)}")

    return sensitive_columns

# Run detection
if CONFIG["pii_enabled"]:
    sensitive_columns_info = detect_sensitive_columns(df, sample_size)
    sensitive_column_names = [c["column"] for c in sensitive_columns_info]

    print(f"\\n✓ Detection complete:")
    print(f"  Total columns scanned: {len(df.columns)}")
    print(f"  Sensitive columns found: {len(sensitive_column_names)}")
    if sensitive_column_names:
        print(f"  Columns: {sensitive_column_names}")
else:
    sensitive_columns_info = []
    sensitive_column_names = []
    print("PII detection disabled")
'''

        return self._create_cell(code, "PII Detection")

    def _generate_masking_functions_cell(self) -> Dict[str, Any]:
        """Generate the masking functions cell."""

        code = '''# Cell 6: Masking Functions
# ============================================================================
# Different masking strategies based on user selection
# ============================================================================

def create_masking_function(masking_type: str):
    """
    Create a masking function based on user's choice.

    Args:
        masking_type: One of 'redact', 'partial', 'fake', 'hash'

    Returns:
        Function that masks PII in text
    """

    def redact_mask(text):
        """Replace with entity labels: john@email.com → <EMAIL_ADDRESS>"""
        if text is None or not PRESIDIO_AVAILABLE:
            return text
        text_str = str(text).strip()
        if not text_str:
            return text
        try:
            results = analyzer.analyze(text=text_str, language='en')
            if results:
                anonymized = anonymizer.anonymize(text=text_str, analyzer_results=results)
                return anonymized.text
            return text
        except:
            return text

    def partial_mask(text):
        """Partial masking: john@email.com → j***@***.com"""
        if text is None or not PRESIDIO_AVAILABLE:
            return text
        text_str = str(text).strip()
        if not text_str:
            return text
        try:
            results = analyzer.analyze(text=text_str, language='en')
            if results:
                operators = {
                    "DEFAULT": OperatorConfig(
                        "mask",
                        {"chars_to_mask": 8, "masking_char": "*", "from_end": False}
                    )
                }
                anonymized = anonymizer.anonymize(
                    text=text_str,
                    analyzer_results=results,
                    operators=operators
                )
                return anonymized.text
            return text
        except:
            return text

    def fake_mask(text):
        """Replace with fake data: john@email.com → user_8x7k@masked.com"""
        if text is None or not PRESIDIO_AVAILABLE:
            return text
        text_str = str(text).strip()
        if not text_str:
            return text
        try:
            results = analyzer.analyze(text=text_str, language='en')
            if results:
                entity_type = results[0].entity_type
                # Generate consistent fake value based on hash
                hash_val = hashlib.md5(text_str.encode()).hexdigest()[:8]
                fake_values = {
                    "EMAIL_ADDRESS": f"user_{hash_val}@masked.com",
                    "PHONE_NUMBER": f"555-{hash_val[:3]}-{hash_val[3:7]}",
                    "US_SSN": "XXX-XX-XXXX",
                    "PERSON": f"Person_{hash_val[:6]}",
                    "CREDIT_CARD": "XXXX-XXXX-XXXX-XXXX",
                    "IP_ADDRESS": "XXX.XXX.XXX.XXX",
                    "LOCATION": "LOCATION_MASKED",
                    "ADDRESS": "ADDRESS_MASKED",
                }
                return fake_values.get(entity_type, f"<{entity_type}>")
            return text
        except:
            return text

    def hash_mask(text):
        """One-way hash: john@email.com → a1b2c3d4e5f6..."""
        if text is None or not PRESIDIO_AVAILABLE:
            return text
        text_str = str(text).strip()
        if not text_str:
            return text
        try:
            results = analyzer.analyze(text=text_str, language='en')
            if results:
                return hashlib.sha256(text_str.encode()).hexdigest()[:16]
            return text
        except:
            return text

    # Return appropriate function
    mask_functions = {
        "redact": redact_mask,
        "partial": partial_mask,
        "fake": fake_mask,
        "hash": hash_mask,
    }

    return mask_functions.get(masking_type, redact_mask)

print(f"✓ Masking functions loaded")
print(f"  Selected masking type: {CONFIG['masking_type']}")
'''

        return self._create_cell(code, "Masking Functions")

    def _generate_apply_masking_cell(self, config: PipelineConfig) -> Dict[str, Any]:
        """Generate the apply masking cell."""

        code = '''# Cell 7: Apply Masking to Sensitive Columns
# ============================================================================
# Applies the user-selected masking type to all detected sensitive columns
# ============================================================================

if CONFIG["pii_enabled"] and sensitive_column_names and PRESIDIO_AVAILABLE:
    # Get masking function
    mask_function = create_masking_function(CONFIG["masking_type"])
    mask_udf = udf(mask_function, StringType())

    # Apply masking to each sensitive column
    df_masked = df
    for column_name in sensitive_column_names:
        print(f"  Masking column: {column_name}")
        df_masked = df_masked.withColumn(column_name, mask_udf(col(column_name)))

    print(f"\\n✓ Masking complete")
    print(f"  Columns masked: {len(sensitive_column_names)}")
    print(f"  Masking type: {CONFIG['masking_type']}")

    # Show sample of masked data
    print("\\nSample of masked data:")
    df_masked.select(sensitive_column_names[:3] if len(sensitive_column_names) > 3 else sensitive_column_names).limit(3).show(truncate=False)
else:
    df_masked = df
    if CONFIG["pii_enabled"]:
        print("No sensitive columns detected or Presidio not available")
    else:
        print("PII masking disabled - using original data")
'''

        return self._create_cell(code, "Apply Masking")

    def _generate_transformations_cell(self, config: PipelineConfig) -> Dict[str, Any]:
        """Generate the transformations cell."""

        transformation_code = "df_transformed = df_masked\n\n"

        for step in config.transformations.steps:
            if step.type == TransformationType.FILTER:
                condition = step.condition or "1=1"
                transformation_code += f'# Filter transformation\ndf_transformed = df_transformed.filter("{condition}")\n'

            elif step.type == TransformationType.SELECT:
                if step.columns:
                    cols = ", ".join([f'"{c}"' for c in step.columns])
                    transformation_code += f'# Select columns\ndf_transformed = df_transformed.select({cols})\n'

            elif step.type == TransformationType.CUSTOM:
                if step.custom_code:
                    transformation_code += f'# Custom transformation\n{step.custom_code}\n'

        code = f'''# Cell 8: Apply Transformations
# ============================================================================
# User-specified data transformations
# ============================================================================

{transformation_code}

print(f"✓ Transformations applied")
print(f"  Rows after transformation: {{df_transformed.count():,}}")
'''

        return self._create_cell(code, "Transformations")

    def _generate_write_cell(self, config: PipelineConfig) -> Dict[str, Any]:
        """Generate the write to destination cell."""

        # Determine which dataframe to use
        df_name = "df_transformed" if config.transformations.enabled else ("df_masked" if config.pii.enabled else "df")

        code = f'''# Cell 9: Write to Lakehouse Table
# ============================================================================
# Write processed data to destination
# ============================================================================

output_table = CONFIG["output_table"]
write_mode = CONFIG["write_mode"]

print(f"Writing to table: {{output_table}}")
print(f"Write mode: {{write_mode}}")

try:
    {df_name}.write \\
        .format("delta") \\
        .mode(write_mode) \\
        .saveAsTable(output_table)

    print(f"\\n✓ Data written successfully to: {{output_table}}")

    # Verify
    result_count = spark.table(output_table).count()
    print(f"  Rows in table: {{result_count:,}}")

except Exception as e:
    print(f"✗ Error writing data: {{e}}")
    raise
'''

        return self._create_cell(code, "Write to Destination")

    def _generate_summary_cell(self, config: PipelineConfig) -> Dict[str, Any]:
        """Generate the summary cell."""

        code = '''# Cell 10: Execution Summary
# ============================================================================

print("=" * 60)
print("PIPELINE EXECUTION SUMMARY")
print("=" * 60)
print(f"Source: {CONFIG['source_path']}")
print(f"Format: {CONFIG['source_format']}")
print(f"Total rows processed: {total_rows:,}")

if CONFIG["pii_enabled"]:
    print(f"PII Detection: Enabled")
    print(f"  Sensitive columns found: {len(sensitive_column_names)}")
    print(f"  Masking type: {CONFIG['masking_type']}")
else:
    print(f"PII Detection: Disabled")

print(f"Output table: {CONFIG['output_table']}")
print(f"Write mode: {CONFIG['write_mode']}")
print("=" * 60)
print("✓ Pipeline completed successfully!")
'''

        return self._create_cell(code, "Summary")

    # =========================================================================
    # HELPER METHODS
    # =========================================================================

    def _create_cell(self, code: str, title: str = "") -> Dict[str, Any]:
        """Create a notebook cell."""
        return {
            "cell_type": "code",
            "source": code,
            "metadata": {
                "title": title
            },
            "outputs": [],
            "execution_count": None
        }

    def _build_notebook_structure(
        self,
        name: str,
        cells: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Build the complete notebook structure."""

        notebook_content = {
            "nbformat": 4,
            "nbformat_minor": 5,
            "metadata": {
                "language_info": {
                    "name": "python"
                },
                "kernel_info": {
                    "name": "synapse_pyspark"
                },
                "notebook_name": name,
                "description": "Auto-generated by AI Pipeline Service"
            },
            "cells": cells
        }

        return {
            "name": name,
            "content": notebook_content,
            "content_base64": base64.b64encode(
                json.dumps(notebook_content).encode()
            ).decode()
        }

    # =========================================================================
    # ENVIRONMENT GENERATION
    # =========================================================================

    def generate_environment_yml(self) -> str:
        """Generate environment.yml for Presidio."""

        return '''name: presidio-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - presidio-analyzer>=2.2.0
    - presidio-anonymizer>=2.2.0
    - spacy>=3.5.0
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.5.0/en_core_web_lg-3.5.0.tar.gz
'''

    def get_presidio_libraries(self) -> List[str]:
        """Get list of libraries needed for Presidio environment."""

        return [
            "presidio-analyzer>=2.2.0",
            "presidio-anonymizer>=2.2.0",
            "spacy>=3.5.0",
        ]
